### ISSUE TITLE
Cannot find Python.h, except for in examples

### ISSUE THREAD

**Issue by j0hnm4r5** [chaosct/ofxPython#1]
Examples compile perfectly fine, but Xcode can't find Python.h when creating projects through the default Project Generator.

**Comment by chaosct** [comment]
I am aware of that :(

XCode project generation with Project Generator is a bit tricky (and undocumented), and as I don't own a mac, it's difficult for me to test this.

Patches are welcome ;) !

**Comment by chaosct** [comment]
Solved
