### ISSUE TITLE
OF 0.9 incompatibilties in openFrameworks_wrap.cpp

### ISSUE THREAD

**Issue by joshuajnoble** [chaosct/ofxPython#11]
I see access of private variables:

``` javascript
ofTexture::bUseExternalTextureID
ofTexture::useTextureMatrix
ofTexture::textureMatrix
ofLight::destroy
```

Incorrect args to: 

``` javascript
ofSetupOpenGL()
ofMatrixStack::ofMatrixStack() 
```

I realize this is a huge issue wrapped in a single bug and I've just started looking at ofxPython but is there a way to remove the access to these member variables and use the ofTextureParams object? Happy to look at it myself as well.

**Comment by chaosct** [comment]
This addon uses the [swig openFrameworks bindings](https://github.com/danomatika/swig-openframeworks) to interface Python with openFrameworks. Sadly, these bindings only support OF version 0.8.4 (you can add an issue there).

To get it working with OF 0.9 new bindings have to be created. If you want to try out to adapt them yourself, just clone this addon with `git clone --recursive` and mess up with the definitions in the `swig-of` folder. Then run swig using the `generatebindings.sh` script to regenerate `openFrameworks_wrap.cpp`.

**Comment by joshuajnoble** [comment]
Ah, ok, I didn't realize that was where those were located. I'll add the issue there and mess with it. Thanks!
