### ISSUE TITLE
sending message back to C++

### ISSUE THREAD

**Issue by estock** [chaosct/ofxPython#3]
Is it possible to send a message back to C++ from python? Perhaps a callback or a simple mechanism?

**Comment by chaosct** [comment]
At the moment it is no possible AFAIK.
I was just now looking into this possibility, so this should be possible in the near future.

**Comment by chaosct** [comment]
@estock I'm implementing this on the [feature_callback](https://github.com/chaosct/ofxPython/tree/feature_callbacks) branch. You can look at the example_Callbacks as a reference (I didn't yet generate the OSX project file, but copying it from another example and adding `ofxPythonCallBack.cpp` in the sources should suffice).

Any comments are welcome :)

**Comment by chaosct** [comment]
This should be integrated now in the master branch with 52257f002c6376ab5ea59c0e244efac94d7e10a8. See `example_CallBacks`.
I'll close this issue when I regenerate the XCode project.

**Comment by chaosct** [comment]
Done :)
